-- Q1. What is the total revenue generated by male vs female customers ?
select gender, sum(purchase_amount) as revenue
from cleaned_data;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from cleaned_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from cleaned_data);

-- Q3. Which are the top 5 products with the highest average review raiting? 
select item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from cleaned_data
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amount between Standard and Express Shipping ?
select shipping_type, round(avg(purchase_amount),2)
from cleaned_data
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5. Do subsscibed customer spend more? Compare average spend and total revenue between subscribers and non-subscribers ?
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from cleaned_data
group by subscription_status
order by total_revenue, avg_spend desc;
 
 
 -- Q6. Which 5 products have the highest percentage of purchases with discount applied ?
 select item_purchased,
 round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*) ,2) as discount_rate
 from cleaned_data
 group by item_purchased
 order by discount_rate desc
 limit 5;
  
  -- Q7. What is the revenue contribution of each age group?
  select age_group,
  sum(purchase_amount) as total_revenue 
  from cleaned_data
  group by age_group
  order by total_revenue desc;
